### ISSUE TITLE
Operation timed out for an unknown reason

### ISSUE THREAD

**Issue by rwmartinez** [Vincit/tarn.js#43] opened 2020-01-23 15:19 UTC
I have a web app that keeps crashing with this error:

* 2020-01-23T08:07:36.485-05:00 [APP/PROC/WEB/0] [ERR] (node:134) UnhandledPromiseRejectionWarning: Error: operation timed out for an unknown reason
* 2020-01-23T08:07:36.485-05:00 [APP/PROC/WEB/0] [ERR] at /home/vcap/app/node_modules/tarn/lib/PendingOperation.js:16:27
* 2020-01-23T08:07:36.485-05:00 [APP/PROC/WEB/0] [ERR] (node:134) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 140)

Searched far and wide but can't pinpoint the exact database call that's triggering this. Attempts to resolve have included specifying Node version 13.5.0, increasing max pool size, updating all npm packages. 

Any help is appreciated.

**Comment by elhigu** [comment] 2020-01-23 19:08
Do you have any reproduction for this. This might as well has nothing to do with tarn and just some handler functions for creating / destroying resources might be badly written. Tarn itself does not contain any database code for example. 

Anyways thing seems to be that for some reason some operation in tarn is timing out and that timeout error is not handled properly... like `pendingOperation.promise` somewhere is not having the error handler set... 

However I checked all places where new PendingOperation is created and didn't see any operations created, where there would not exist an error handler: https://github.com/Vincit/tarn.js/blob/73f3e80e470a1d9612ec6b3465217b0fa8966bed/src/Pool.ts

**Comment by elhigu** [comment] 2020-03-02 07:50
Closing as cannot reproduce.

**Closed by elhigu** 2020-03-02 07:50 UTC

**Comment by yasharma** [comment] 2021-02-14 19:55
Hi, i'm facing the same issue, 
```sh
Error: operation timed out for an unknown reason
at PendingOperation.promise.timeout.catch.err (/app/node_modules/tarn/lib/PendingOperation.js:16:27)
t propagateAslWrapper (/app/node_modules/async-listener/index.js:504:23)
at /app/node_modules/async-listener/glue.js:188:31
at /app/node_modules/async-listener/index.js:541:70
at /app/node_modules/async-listener/glue.js:188:31
```
this is only happening when Query is fired simultaneously and during this operation network connectivity is dropped, once network is back same error is keep on coming, until service restarted and new connection established.

to reproduce this following config : 

```javascript
const configDB = {
  user: config.sqlDbUsername,
  password: config.sqlDbPassword,
  port: config.sqlDbPort,
  server: config.sqlDbHost,
  database: config.sqlDbName,
  pool: {
    max: 1,
  },
};
let _connection: Promise<sql.ConnectionPool>;
export const setupDB = () => {
  try {
    const _pool = new sql.ConnectionPool(configDB);
    _connection = _pool.connect();
    logger.info('DB Connection is ready ...');
    _pool.on('error', error => {
      logger.error('DB Error handler :', error);
    });
  } catch (err) {
    logger.error('Failed to Initialize the socket:', err);
    throw err;
  }
};
export const getConnectionPool = () => {
  return _connection;
};

async function fetchData() {
  const _pool = await getConnectionPool();
  const _request = new PreparedStatement(_pool);
  await _request.prepare(query); // pass sample query
  const { recordsets } = await _request.execute(data);
  await _request.unprepare();
  return recordsets;
}
```
I'm executing parallel query using prepare statement, and with pool.max is 1

**Comment by elhigu** [comment] 2021-02-17 12:21
@yasharma if you are able to reproduce this without any additional library; please open a bug report. Otherwise it looks like usage or `sql` library error.

**Comment by yasharma** [comment] 2021-02-23 13:34
@elhigu Yes, i'm using node-mssql (https://github.com/tediousjs/node-mssql), that library internal using tarn, so directly i can reproduce this, but if someone knows any reference and issue associated with this, please provide reference, as i'm searching on multiple places but not getting any working solution, anyways thanks @elhigu

**Comment by kibertoad** [comment] 2021-02-23 13:52
@yasharma TBH, connection pooling for mssql is hopelessly broken in current knext stable. I would definitely recommend trying 0.95.0-next3 instead (it will be released as a stable in 1-2 weeks with very negligible changes, should be safe to use it in production already).

**Comment by yasharma** [comment] 2021-02-24 10:01
@kibertoad Thanks for update on Knex, however i'm bit confuse with Knex and Node-Mssql, can you elaborate, because i'm not using knex directly. Thanks

**Comment by laychopy** [comment] 2021-07-17 13:03
Hi, @yasharma Do you found some help? I facing the same problem.

**Comment by yasharma** [comment] 2021-07-18 06:35
@laychopy I've handled this issue with different approach, i've listen for the error event (https://github.com/tediousjs/node-mssql#connect-callback) along with Error code `ETIMEOUT`, and again retry the connection within some interval, so every time if i'll get `operation timed out` with error code, it will keep on retry connection until success , 

Here is the sample code
```typescript
const handleDBError = (error: sql.ConnectionError) => {
  logger.error('DB Error handler: ', error);
  if (error.message.includes('operation timed out') || error.code === 'ETIMEOUT') {
    clearInterval(timer);
    timer = setInterval(() => {
      return void (async () => {
        try {
          logger.info(`Retrying connection ... `);
          await setupDB();
        } catch (error) {
          logger.error('Error connecting ...');
        }
      })();
    }, config.retryConnectionInterval);
  }
};

export const setupDB = async () => {
  try {
    _pool = new sql.ConnectionPool(configDB);
    await _pool.connect();
    clearInterval(timer); // clear the interval once the connection established
    logger.info('DB Connection successful ...');
    _pool.on('error', handleDBError);
  } catch (err) {
    logger.error('Failed to connect:', err);
    const _err = <sql.ConnectionError>err;
    if (_err.code === 'ETIMEOUT') handleDBError(err);
    throw err;
  }
};
```

Hope this helps you

**Comment by rasmusrim** [comment] 2022-03-30 11:20
I know this is an old issue, I just want to share the way I solved it since this solution did not help me. I found some obscure timeout settings under "pool" which I increased to a ridiculous amount. I am not sure which one of these helped, but this solved my problem:

```
      const timeout = 120_000_000;

      const pool = new sql.ConnectionPool({
        user: env.DB_USERNAME,
        password: env.DB_PASSWORD,
        server: env.DB_HOST,
        database: env.DB_DATABASE_NAME,
        options: { trustServerCertificate: true },
        requestTimeout: timeout,
        pool: {
          max: 1000, min: 1,
          idleTimeoutMillis: timeout,
          acquireTimeoutMillis: timeout,
          createTimeoutMillis: timeout,
          destroyTimeoutMillis: timeout,
          reapIntervalMillis: timeout,
          createRetryIntervalMillis: timeout,
        }
      });

```

**Comment by perry-mitchell** [comment] 2022-04-27 08:21
I'm seeing this issue now in production, using Redis (not that it matters) as the resource. I'd happily build a minimal reproduction but it seems like it happens quite infrequently. Of our 16+ running pods on k8s, only 6 failures have been noticed over 24 hours, and there's nothing there to really indicate what changed. Race condition most likely.

Seems that something just dies when it's trying to handle an acquire timeout:

```
/data/node_modules/tarn/dist/PendingOperation.js:17
                    err = new TimeoutError_1.TimeoutError('operation timed out for an unknown reason');
                          ^
TimeoutError: operation timed out for an unknown reason
    at /data/node_modules/tarn/dist/PendingOperation.js:17:27
    at runNextTicks (node:internal/process/task_queues:61:5)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
    at async ConnectionPool.acquireConnection (/data/node_modules/@x/redis-connection-pool/dist/ConnectionPool.js:53:24)
    at async ConnectionPool.use (/data/node_modules/@x/redis-connection-pool/dist/ConnectionPool.js:74:28)
```

**Comment by onzag** [comment] 2022-08-22 08:08
I am having this same issue but I am using tarn directly to manage some server resources that are used in a pool, after some time the server responds with that error.

@elhigu you seem knowledgeable, what is your theory this could be happening so at least I get a lead, right now I just restart the server but I am not doing anything too complex, I have a stateful object that is used per request, HTTP requests of course can be simultaneous, causing pollution, so I created a pool of that object with many instances of it.

```
/**
 * Provides a pool of root
 * @param rawData the root raw data
 */
export function retrieveRootPool(rawData: IRootRawJSONDataType): Pool<Root> {
  const pool: Pool<Root> = new Pool({
    create: (cb) => {
      cb(null, new Root(rawData));
    },
    validate: () => {
      return true;
    },
    destroy: () => {
      // if the object is destroyed so all its memory addresses
      // so no need for manual cleanup when javacript garbage collector
      // can collect all the slots
      return;
    },
    log: (message) => {
      CAN_LOG_DEBUG && logger.debug(
        {
          message,
          functionName: "retrieveRootPool",
        }
      );
    },
    min: 10,
    max: 100,
    acquireTimeoutMillis: 1000,
    createTimeoutMillis: 1000,
    destroyTimeoutMillis: 300,
    idleTimeoutMillis: 30000,
    reapIntervalMillis: 1000,
    createRetryIntervalMillis: 1,
    propagateCreateError: true,
  });
  return pool;
}
```

Currently my theory is that an error is being triggered inbetween the adquire and the release and the release is never being executed. I found that if a rare exception during database write occurred, say, network is down, the root wouldn't be released and it will instantly go to internal server error, but I am not sure. Error occurred after 1 month server running, can't wait that long to see if it was that, any other theories.

**Comment by elhigu** [comment] 2022-08-22 09:23
@onzag if I understood correctly,  you are having pool of state objects whose creation is pretty resource intensive operation, which is the reason why you want to prevent creating / destroying per each request?

I would suggest to add some debug information to the pool operations and print out for example every 10 minutes how many objects are leased from the pool. If that number is raising all the time it might suggest that there is a problem where you are checking out objects from the pool, but for some reason (for example on unexpected error) the resource is not returned when the request handling is interrupted.

If you add also debug prints about acquired and released resources it might show that your app is leaking them:

```
pool.on('acquireSuccess', (eventId, resource) => { /* log the acquired resource id here */ });
pool.on('release', resource => { /* log the released resource id here */ });
```

> Currently my theory is that an error is being triggered inbetween the adquire and the release and the release is never being executed.

Yep that is the most common reason and Tarn does not provide any timers for limiting the lease time of a resource.

Though it shouldn't be too difficult to add a timestamp to the leased resource when it was leased and then call release for it if the lease time is too long in the past. Or one could even add the setTimeout() to the object which automatically releases the resource if it is left outside of the pool for a too long time (then one should clear that timeout when resource is release back to the pool).

**Comment by onzag** [comment] 2022-08-22 17:17
@elhigu alright those are some interesing events, yep you are right, it's an object that represents the client side app state, while the state is simple, the tracker itself, it's kinda big.

Oh I thought it would give me an error where like, "could not adquire resource because not a single instance was free" or something more meaningful than "unknown reason".

I guess I can use the adquireSuccess and release to set a timeout there, these resources are defenitely not used more than 10 seconds; they exist only during http requests.

Doesn't that mean that the server can be overwhelmed by multiple simultaneous requests that are greater than the amount of max objects I can provide?...

**Comment by elhigu** [comment] 2022-08-24 08:08
@onzag probably you would like to have amount of max objects greater than maximum number of concurrent requests.

**Comment by isaackogan** [comment] 2023-06-27 04:45
> I know this is an old issue, I just want to share the way I solved it since this solution did not help me. I found some obscure timeout settings under "pool" which I increased to a ridiculous amount. I am not sure which one of these helped, but this solved my problem:
> 
> ```
>       const timeout = 120_000_000;
> 
>       const pool = new sql.ConnectionPool({
>         user: env.DB_USERNAME,
>         password: env.DB_PASSWORD,
>         server: env.DB_HOST,
>         database: env.DB_DATABASE_NAME,
>         options: { trustServerCertificate: true },
>         requestTimeout: timeout,
>         pool: {
>           max: 1000, min: 1,
>           idleTimeoutMillis: timeout,
>           acquireTimeoutMillis: timeout,
>           createTimeoutMillis: timeout,
>           destroyTimeoutMillis: timeout,
>           reapIntervalMillis: timeout,
>           createRetryIntervalMillis: timeout,
>         }
>       });
> ```

Terrible idea, will cause you to run out of connections in the pool
